name: CI-CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker
        run: docker build -t app .

      - name: Run container
        run: docker run -d -p 8080:80 app
